# Generated by Django 4.1.2 on 2022-10-31 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request_app', '0007_alter_requests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.IntegerField(default=1, verbose_name='Статус заявки'),
        ),
        migrations.DeleteModel(
            name='StatusNames',
        ),
    ]
